apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 3 # number of instances of our app running
  selector: # make sure our deployment deploys correct application
    matchLabels:
      app: auth
  template: # actual information about the app run
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: audiph/ordering-app_auth # Docker image built
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: '3001'
            - name: RABBIT_MQ_BILLING_QUEUE
              value: billing
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
            - name: JWT_EXPIRATION
              value: '3600'
            - name: JWT_SECRET
              value: 746fc30ec833fab7ce6164c215e14c0adbb6bb386f52d34c1f36cfd979758ef9
