apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001 # where our app is listening from k8s
  selector: # tells the service where to route the traffic to
    app: auth
