apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 3 # number of instances of our app running
  selector: # make sure our deployment deploys correct application
    matchLabels:
      app: orders
  template: # actual information about the app run
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: audiph/ordering-app_orders # Docker image built
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: RABBIT_MQ_BILLING_QUEUE
              value: billing
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
