apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000 # where our app is listening from k8s
  selector: # tells the service where to route the traffic to
    app: orders
